-- ttc-mm compat addon: TamrielTradeCentre/Bootstrap.lua
-- Auto-generated by ttc-mm.  DO NOT EDIT -- overwritten on each update.
-- Registers EVENT_ADD_ON_LOADED to initialise the item lookup table and the
-- region-appropriate price table so that GetPriceInfo works immediately.

local function OnAddOnLoaded(eventCode, addOnName)
	if addOnName ~= "TamrielTradeCentre" then return end
	EVENT_MANAGER:UnregisterForEvent("TamrielTradeCentre", EVENT_ADD_ON_LOADED)

	-- Load item name → TTC ID lookup table (populated by ItemLookUpTable_EN.lua).
	if TamrielTradeCentre.LoadItemLookUpTable ~= nil then
		TamrielTradeCentre:LoadItemLookUpTable()
	end

	-- Load the region-appropriate price table (populated by PriceTable{NA,EU}.lua).
	local serverRegion = TamrielTradeCentre:GetCurrentServerRegion()
	if serverRegion == "NA" and TamrielTradeCentrePrice.LoadPriceTableNA ~= nil then
		TamrielTradeCentrePrice:LoadPriceTableNA()
	elseif serverRegion == "EU" and TamrielTradeCentrePrice.LoadPriceTableEU ~= nil then
		TamrielTradeCentrePrice:LoadPriceTableEU()
	end
end

EVENT_MANAGER:RegisterForEvent("TamrielTradeCentre", EVENT_ADD_ON_LOADED, OnAddOnLoaded)
