-- ttc-mm compat addon: TamrielTradeCentre/Init.lua
-- Auto-generated by ttc-mm.  DO NOT EDIT -- overwritten on each update.
-- Source sections taken verbatim from TamrielTradeCentreInit.lua and
-- TamrielTradeCentre.lua (public API subset required by Master Merchant).

TamrielTradeCentre = {}
TamrielTradeCentre.IsDebug = false
TamrielTradeCentre.AddonName = "TamrielTradeCentre"

function TamrielTradeCentre:DebugWriteLine(msg)
	if (self.IsDebug) then
		d(msg)
	end
end

function TamrielTradeCentre:IsStringNilOrEmpty(s)
	return s == nil or s == ""
end

function TamrielTradeCentre:FormatNumber(number, decimal)
	local mult = 10 ^ (decimal or 2)
	number = math.floor(number * mult + 0.5) / mult

	local i, j, minus, int, fraction = tostring(number):find('([-]?)(%d+)([.]?%d*)')
	int = int:reverse():gsub("(%d%d%d)", "%1,")
	return minus .. int:reverse():gsub("^,", "") .. fraction
end

function TamrielTradeCentre:IsItemLink(link)
	local _, _, linkType = ZO_LinkHandler_ParseLink(link)
	return linkType == "item"
end

function TamrielTradeCentre:GetCurrentServerRegion()
	local serverRegion = nil
	local lastPlatform = GetCVar("LastPlatform")
	local lastRealm = GetCVar("LastRealm")
	if (lastPlatform == "Live") then
		serverRegion = "NA"
	elseif (lastPlatform == "Live-EU") then
		serverRegion = "EU"
	elseif (lastRealm ~= nil and lastRealm:find("^NA") ~= nil) then
		serverRegion = "NA"
	elseif (lastRealm ~= nil and lastRealm:find("^EU") ~= nil) then
		serverRegion = "EU"
	end
	return serverRegion
end

------------------------------------------------------------------------------------------------------------

TamrielTradeCentrePrice = {}

------------------------------------------------------------------------------------------------------------

TamrielTradeCentre_PriceInfo = {}
function TamrielTradeCentre_PriceInfo:New(avg, max, min, entryCount, amountCount, suggestedPrice, saleAvg, saleEntryCount, saleAmountCount)
	local priceInfo = {}
	priceInfo.Avg = avg
	priceInfo.Max = max
	priceInfo.Min = min
	priceInfo.EntryCount = entryCount
	priceInfo.AmountCount = amountCount
	priceInfo.SuggestedPrice = suggestedPrice
	priceInfo.SaleAvg = saleAvg
	priceInfo.SaleEntryCount = saleEntryCount
	priceInfo.SaleAmountCount = saleAmountCount

	return priceInfo
end

------------------------------------------------------------------------------------------------------------

TamrielTradeCentre_ItemInfo = {}

function TamrielTradeCentre_ItemInfo:TraitTypeToTraitID(traitType)
	if (traitType == ITEM_TRAIT_TYPE_ARMOR_DIVINES) then
		return 13
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_PROSPEROUS) then
		return 12
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE) then
		return 9
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_INFUSED or traitType == ITEM_TRAIT_TYPE_WEAPON_INFUSED or traitType == ITEM_TRAIT_TYPE_JEWELRY_INFUSED) then
		return 3
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_INTRICATE or traitType == ITEM_TRAIT_TYPE_WEAPON_INTRICATE or traitType == ITEM_TRAIT_TYPE_JEWELRY_INTRICATE) then
		return 15
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_NIRNHONED or traitType == ITEM_TRAIT_TYPE_WEAPON_NIRNHONED) then
		return 14
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_ORNATE or traitType == ITEM_TRAIT_TYPE_WEAPON_ORNATE or traitType == ITEM_TRAIT_TYPE_JEWELRY_ORNATE) then
		return 16
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_REINFORCED) then
		return 10
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_STURDY) then
		return 8
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_TRAINING or traitType == ITEM_TRAIT_TYPE_WEAPON_TRAINING) then
		return 5
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED) then
		return 11
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_ARCANE) then
		return 17
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_HEALTHY) then
		return 18
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_ROBUST) then
		return 19
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY) then
		return 21
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_HARMONY) then
		return 22
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE) then
		return 23
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_SWIFT) then
		return 24
	elseif (traitType == ITEM_TRAIT_TYPE_JEWELRY_TRIUNE) then
		return 25
	elseif (traitType == ITEM_TRAIT_TYPE_WEAPON_CHARGED) then
		return 1
	elseif (traitType == ITEM_TRAIT_TYPE_WEAPON_DEFENDING) then
		return 4
	elseif (traitType == ITEM_TRAIT_TYPE_WEAPON_POWERED) then
		return 0
	elseif (traitType == ITEM_TRAIT_TYPE_WEAPON_PRECISE) then
		return 2
	elseif (traitType == ITEM_TRAIT_TYPE_WEAPON_SHARPENED) then
		return 6
	elseif (traitType == ITEM_TRAIT_TYPE_WEAPON_DECISIVE) then
		return 7
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_AGGRESSIVE or traitType == ITEM_TRAIT_TYPE_JEWELRY_AGGRESSIVE or traitType == ITEM_TRAIT_TYPE_WEAPON_AGGRESSIVE) then
		return 26
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_AUGMENTED or traitType == ITEM_TRAIT_TYPE_JEWELRY_AUGMENTED or traitType == ITEM_TRAIT_TYPE_WEAPON_AUGMENTED) then
		return 27
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_BOLSTERED or traitType == ITEM_TRAIT_TYPE_JEWELRY_BOLSTERED or traitType == ITEM_TRAIT_TYPE_WEAPON_BOLSTERED) then
		return 28
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_FOCUSED or traitType == ITEM_TRAIT_TYPE_JEWELRY_FOCUSED or traitType == ITEM_TRAIT_TYPE_WEAPON_FOCUSED) then
		return 29
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_PROLIFIC or traitType == ITEM_TRAIT_TYPE_JEWELRY_PROLIFIC or traitType == ITEM_TRAIT_TYPE_WEAPON_PROLIFIC) then
		return 30
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_QUICKENED or traitType == ITEM_TRAIT_TYPE_JEWELRY_QUICKENED or traitType == ITEM_TRAIT_TYPE_WEAPON_QUICKENED) then
		return 31
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_SHATTERING or traitType == ITEM_TRAIT_TYPE_JEWELRY_SHATTERING or traitType == ITEM_TRAIT_TYPE_WEAPON_SHATTERING) then
		return 32
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_SOOTHING or traitType == ITEM_TRAIT_TYPE_JEWELRY_SOOTHING or traitType == ITEM_TRAIT_TYPE_WEAPON_SOOTHING) then
		return 33
	elseif (traitType == ITEM_TRAIT_TYPE_ARMOR_VIGOROUS or traitType == ITEM_TRAIT_TYPE_JEWELRY_VIGOROUS or traitType == ITEM_TRAIT_TYPE_WEAPON_VIGOROUS) then
		return 34
	end

	return nil
end

function TamrielTradeCentre_ItemInfo:ArmorTypeToCategory2OverWrite(armorType)
	if (armorType == ARMORTYPE_HEAVY) then
		return 4
	elseif (armorType == ARMORTYPE_MEDIUM) then
		return 3
	elseif (armorType == ARMORTYPE_LIGHT) then
		return 2
	end

	return nil
end

function TamrielTradeCentre_ItemInfo:PotionEffectCodeToID(isPoison, effectID)
	if (not isPoison) then
		if (effectID == 1) then return 0   --Restore Health
		elseif (effectID == 2) then return 13  --Ravage Health
		elseif (effectID == 3) then return 1   --Restore Magicka
		elseif (effectID == 4) then return 14  --Ravage Magicka
		elseif (effectID == 5) then return 2   --Restore Stamina
		elseif (effectID == 6) then return 15  --Ravage Stamina
		elseif (effectID == 7) then return 7   --Spell Resistance
		elseif (effectID == 8) then return 20  --Lower Spell Resis (breach)
		elseif (effectID == 9) then return 8   --Increase armor
		elseif (effectID == 10) then return 21 --Lower Armor (Fracture)
		elseif (effectID == 11) then return 5  --Increase Spell Power
		elseif (effectID == 12) then return 17 --Lower Spell Power
		elseif (effectID == 13) then return 6  --Increase Weapon Power
		elseif (effectID == 14) then return 18 --Lower Weapon Power
		elseif (effectID == 15) then return 3  --Spell Critical
		elseif (effectID == 16) then return 58 --Lower Spell Critical
		elseif (effectID == 17) then return 4  --Weapon Critical
		elseif (effectID == 18) then return 16 --Lower Weapon Critical
		elseif (effectID == 19) then return 12 --unstoppable
		elseif (effectID == 20) then return 23 --Stun
		elseif (effectID == 21) then return 9  --Detection
		elseif (effectID == 22) then return 10 --Invisible
		elseif (effectID == 23) then return 11 --Speed
		elseif (effectID == 24) then return 22 --Reduce speed
		elseif (effectID == 25) then return 24 --Reduce damage taken (Protection)
		elseif (effectID == 26) then return 28 --increase damage taken
		elseif (effectID == 27) then return 25 --sustain restore health
		elseif (effectID == 28) then return 27 --gradual ravage health
		elseif (effectID == 29) then return 19 --Increase Healing taken (Vitality)
		elseif (effectID == 30) then return 26 --Lower Healing taken (Defile)
		end
	else
		if (effectID == 1) then return 29  --Restore Health
		elseif (effectID == 2) then return 42  --Ravage Health
		elseif (effectID == 3) then return 30  --Restore Magicka
		elseif (effectID == 4) then return 43  --Ravage Magicka
		elseif (effectID == 5) then return 31  --Restore Stamina
		elseif (effectID == 6) then return 44  --Ravage Stamina
		elseif (effectID == 7) then return 36  --Spell Resistance
		elseif (effectID == 8) then return 49  --Lower Spell Resis (breach)
		elseif (effectID == 9) then return 37  --Increase armor
		elseif (effectID == 10) then return 50 --Lower Armor (Fracture)
		elseif (effectID == 11) then return 34 --Increase Spell Power
		elseif (effectID == 12) then return 46 --Lower Spell Power
		elseif (effectID == 13) then return 35 --Increase Weapon Power
		elseif (effectID == 14) then return 47 --Lower Weapon Power
		elseif (effectID == 15) then return 32 --Spell Critical
		elseif (effectID == 16) then return 59 --Lower Spell Critical
		elseif (effectID == 17) then return 33 --Weapon Critical
		elseif (effectID == 18) then return 45 --Lower Weapon Critical
		elseif (effectID == 19) then return 41 --unstoppable
		elseif (effectID == 20) then return 52 --Stun
		elseif (effectID == 21) then return 38 --Detection
		elseif (effectID == 22) then return 39 --Invisible
		elseif (effectID == 23) then return 40 --Speed
		elseif (effectID == 24) then return 51 --Reduce speed
		elseif (effectID == 25) then return 53 --Reduce damage taken (Protection)
		elseif (effectID == 26) then return 57 --increase damage taken
		elseif (effectID == 27) then return 54 --sustain restore health
		elseif (effectID == 28) then return 56 --gradual ravage health
		elseif (effectID == 29) then return 48 --Increase Healing taken (Vitality)
		elseif (effectID == 30) then return 55 --Lower Healing taken (Defile)
		end
	end

	return nil
end

function TamrielTradeCentre_ItemInfo:SetCodeToID(setCode)
	if (setCode == 0) then
		return nil
	end

	return setCode
end

function TamrielTradeCentre_ItemInfo:StyleCodeToID(styleCode)
	if (styleCode == 0) then
		return nil
	end

	return styleCode
end

function TamrielTradeCentre_ItemInfo:NameSpecializedItemTypeToItemID(itemName, specializedItemType)
	itemName = string.lower(itemName)

	if (TamrielTradeCentre.ItemLookUpTable == nil) then
		return nil
	end

	local specializedItemTypeTable = TamrielTradeCentre.ItemLookUpTable[itemName]
	if (specializedItemTypeTable == nil) then
		return nil
	end

	if (specializedItemType == nil) then
		for key, value in pairs(specializedItemTypeTable) do
			return value
		end

		return nil
	end

	return specializedItemTypeTable[specializedItemType]
end

local function BitAnd(a, b)
	local result = 0
	local bitval = 1
	while a > 0 and b > 0 do
		if a % 2 == 1 and b % 2 == 1 then
			result = result + bitval
		end
		bitval = bitval * 2
		a = math.floor(a / 2)
		b = math.floor(b / 2)
	end
	return result
end

local function BitRightShift(number, by)
	return math.floor(number / 2 ^ by)
end

function TamrielTradeCentre_ItemInfo:New(itemLink)
	if (not TamrielTradeCentre:IsItemLink(itemLink)) then
		TamrielTradeCentre:DebugWriteLine("price table nil or not an item link")
		return nil
	end

	local itemName = GetItemLinkName(itemLink)
	local itemQuality = GetItemLinkQuality(itemLink)
	local requiredLevel = GetItemLinkRequiredLevel(itemLink)
	local requiredChampionPoint = GetItemLinkRequiredChampionPoints(itemLink)
	local traitType, _ = GetItemLinkTraitInfo(itemLink)
	local itemType, specializedItemType = GetItemLinkItemType(itemLink)
	local armorType = GetItemLinkArmorType(itemLink)
	local itemLinkParams = {ZO_LinkHandler_ParseLink(itemLink)}
	local lastParam = itemLinkParams[24]

	local itemInfo = {}
	itemInfo.ItemLink = itemLink
	itemInfo.Name = zo_strformat(SI_TOOLTIP_ITEM_NAME, itemName)
	itemInfo.QualityID = itemQuality - 1
	itemInfo.ID = self:NameSpecializedItemTypeToItemID(itemInfo.Name, specializedItemType)
	if (itemInfo.QualityID < 0) then
		itemInfo.QualityID = 0
	end

	itemInfo.Level = requiredLevel
	if (requiredChampionPoint > 0) then
		itemInfo.Level = 50 + requiredChampionPoint
	end

	itemInfo.TraitID = self:TraitTypeToTraitID(traitType)
	itemInfo.ItemType = itemType
	itemInfo.Category2IDOverWrite = self:ArmorTypeToCategory2OverWrite(armorType)

	if (itemType == ITEMTYPE_POTION or itemType == ITEMTYPE_POISON) then
		local isPoison = itemType == ITEMTYPE_POISON
		if (lastParam ~= 0) then
			itemInfo.PotionEffects = {}

			for i = 0, 2 do
				local potionEffectCode = BitAnd(BitRightShift(lastParam, i * 8), 0xFF)
				local potionEffectID = self:PotionEffectCodeToID(isPoison, potionEffectCode)
				if (potionEffectID ~= nil) then
					table.insert(itemInfo.PotionEffects, potionEffectID)
				end
			end

			table.sort(itemInfo.PotionEffects)
		end
	elseif (itemType == ITEMTYPE_MASTER_WRIT) then
		-- Master writ pricing requires TTC lang string constants not available in
		-- compat mode.  Setting ID to nil causes GetPriceInfo to return nil.
		itemInfo.ID = nil
	end

	return itemInfo
end

------------------------------------------------------------------------------------------------------------

-- Master writ pricing is not supported in compat mode (no lang string constants).
TamrielTradeCentre_MasterWritInfo = {}
function TamrielTradeCentre_MasterWritInfo:New(itemLink)
	return nil
end
