-- ttc-mm compat addon: TamrielTradeCentre/Price.lua
-- Auto-generated by ttc-mm.  DO NOT EDIT -- overwritten on each update.
-- Source: TamrielTradeCentrePrice:GetPriceInfo taken verbatim from
-- TamrielTradeCentrePrice.lua (the public function Master Merchant calls).

--Public Function. Used by 3rd parties (including Master Merchant).
function TamrielTradeCentrePrice:GetPriceInfo(itemInfoOrLink)
	local itemInfo = itemInfoOrLink
	local typeName = type(itemInfoOrLink)
	if (typeName == "string") then
		itemInfo = TamrielTradeCentre_ItemInfo:New(itemInfoOrLink)
	end

	if (self.PriceTable == nil or itemInfo == nil or itemInfo.ID == nil) then
		return nil
	end

	local itemIDDict = self.PriceTable.Data
	local qualityDict = itemIDDict[itemInfo.ID]
	if (qualityDict == nil) then
		TamrielTradeCentre:DebugWriteLine("itemIDDict not found")
		return nil
	end

	local levelDict = qualityDict[itemInfo.QualityID]
	if (levelDict == nil) then
		TamrielTradeCentre:DebugWriteLine("qualityDict not found")
		return nil
	end

	local traitDict = levelDict[itemInfo.Level]
	if (traitDict == nil) then
		TamrielTradeCentre:DebugWriteLine("levelDict not found")
		return nil
	end

	local priceDict = nil
	if (itemInfo.Category2IDOverWrite ~= nil) then
		local category2Dict = traitDict[itemInfo.TraitID or -1]
		if (category2Dict == nil) then
			TamrielTradeCentre:DebugWriteLine("traitDict not found")
			return nil
		end

		priceDict = category2Dict[itemInfo.Category2IDOverWrite]
	elseif (itemInfo.ItemType == ITEMTYPE_POTION or itemInfo.ItemType == ITEMTYPE_POISON) then
		local potionEffectDict = traitDict[itemInfo.TraitID or -1]
		if (potionEffectDict == nil) then
			TamrielTradeCentre:DebugWriteLine("traitDict not found")
			return nil
		end

		local potionEffectString = ""
		if (itemInfo.PotionEffects ~= nil) then
			for i = 1, #itemInfo.PotionEffects do
				if (potionEffectString ~= "") then
					potionEffectString = potionEffectString .. "|"
				end

				potionEffectString = potionEffectString .. itemInfo.PotionEffects[i]
			end
		end

		priceDict = potionEffectDict[potionEffectString]
	elseif (itemInfo.ItemType == ITEMTYPE_MASTER_WRIT) then
		-- itemInfo.ID is nil for master writs in compat mode; already caught above.
		return nil
	else
		priceDict = traitDict[itemInfo.TraitID or -1]
	end

	if (priceDict == nil or (priceDict.Avg == nil and priceDict.A == nil)) then
		TamrielTradeCentre:DebugWriteLine("priceDict not found")
		return nil
	end

	return TamrielTradeCentre_PriceInfo:New(priceDict.Avg or priceDict.A, priceDict.Max or priceDict.X, priceDict.Min or priceDict.N, priceDict.EntryCount or priceDict.EC, priceDict.AmountCount or priceDict.AC, priceDict.SuggestedPrice or priceDict.S, priceDict.SaleAvg or priceDict.SA, priceDict.SaleEntryCount or priceDict.SE, priceDict.SaleAmountCount or priceDict.SAC)
end
